### ISSUE TITLE
Instead of column name checkbox should be Using Server Side

### ISSUE THREAD

**Issue by shireen22** [yajra/laravel-datatables#1022]
![column name check box](https://cloud.githubusercontent.com/assets/15665520/23161846/7bdae96e-f84d-11e6-8447-cde85310465e.png)

**Comment by umefarooq** [comment]
do you want to use first column as checkbox for all your records, use 
```javascript
 ->editColumn('name', function ($event) {
                return '<input type="checkbox" value="">'; 
  })
```

**Comment by shireen22** [comment]
i use following code it does nt work for me Thanks

**Comment by minedun6** [comment]
The problem is that the column you're trying to edit doesn't exist.
and since you don't have a column that have the name of the column you're trying to call in the ediColumn method, so simply put, use the addColumn('give it a name') and then add it to the list of columns in the getColumns method.
Cheers.
