### ISSUE TITLE
Using Laravel Scout

### ISSUE THREAD

**Issue by peyobr** [yajra/laravel-datatables#1042]
### Summary of problem or feature request

Hi Arjay,

i'm wandering if using your wonderful package in combination with laravel Scout would be a pain... (as far as i know) using Scout i have to call get() after filtering on the index (i have to manage an istance of Laravel\Scout\Builder) ...

Should i convert my code to use a collection data source??? :(

Thank you!!

peyobr

### System details
- Ubuntu 16.4
- PHP 7.0
- Laravel 5.4
- Laravel-Datatables 7

**Comment by yajra** [comment]
I haven't personally used laravel scout. Will give it a shot when I had the chance. Thanks!

**Comment by VRuzhentsov** [comment]
i think, we need another one Engine, maybe extending yours EloquentEngine class, or some parallel. i had began a couple of days ago, but without scout, just with Elastic search. But the attempts were not successful. Today, i'll try to think, how we could at least implement basic scout searching. Maybe later, i'll do another one alpha-scout branch with PR. But these are only approximate plans

**Comment by DMeganoski** [comment]
+1 for this.

Was actually going to open a request for this if there wasn't one already. I know this would be quite a project, though, especially if you haven't worked with scout yet. Would be awesome, though :+1: 

I am also using elasticsearch (with scout) for my general search. I would like to see an option to use the scout driver for search instead of the sql with datatables as well ('LIKE' statements can be a problem with large data sets).

**Comment by andreladocruz** [comment]
+1 For using the Laravel Scout And DataTables. :) 
This would be a great join. :) 
Thanks

**Comment by yajra** [comment]
Had a change to checkout Laravel Scout today and I think I got the necessary info needed to implement this. Will add basic support on Laravel Scout via this plugin repo https://github.com/yajra/laravel-datatables-scout. ^_^

**Comment by forgottencreature** [comment]
Would love to see this worked on a bit more. I've installed the Scout plugin referenced above, however have no clue how to actually implement it.
