### ISSUE TITLE
Request: add support for custom render actions

### ISSUE THREAD

**Issue by underdpt** [yajra/laravel-datatables#1098]
Hi,

Now, the only actions available to render are `['print', 'csv', 'excel', 'pdf']`. The code searchs for the `action` request variable and if it matches any of those, it calls the function of the same name.

Could it be possible to add support for custom actions? If the action param doesn't matches any of the above, but a user function exists with that name, then call it.

**Comment by yajra** [comment]
The restrictions was added for security purposes since a user can hijack the request and set the action value to any valid method name.

Anyways, I am open to the idea of allowing custom actions but I think we should explicitly set a property of allowed actions to limit the access or some other ways that you can think of. Please do not hesitate to submit a PR for possible enhancement. Thanks!

**Comment by underdpt** [comment]
Here you go... 

https://github.com/yajra/laravel-datatables-buttons/pull/18

It's my first PR, be aware :-)

**Comment by yajra** [comment]
Thanks a lot. Simple yet elegant PR. 👍
