### ISSUE TITLE
Documentation site down?

### ISSUE THREAD

**Issue by thelibrariancat** [yajra/laravel-datatables#1127]
Hi! Your site (yajrabox.com) seems to be down. Is the documentation available somewhere else?

**Comment by brucebetts** [comment]
there is non-laravel specific documentation at https://datatables.net

**Comment by ReynerHL** [comment]
@brucebetts That website is only for the datatable project, (Table plug-in for jQuery), so we can't find an specific server side implementation there, maybe some examples using PHP as backend language but not Laravel.

Since some days ago, I've noticed that the doc site has some problems with SSL certificate, and also is very slow. Is there any reason for not using the github wiki section for this project in order to keep update its docs?

(https://github.com/yajra/laravel-datatables/wiki)

Right now, it seems to be outdated but maybe we can help you with this. It is a great project and I suppose that some others would like to help, too.

**Comment by yajra** [comment]
Thanks for reporting. You can access the docs at https://github.com/yajra/laravel-datatables-docs. 

Checking the server, ping @ChaosPower.

**Comment by yajra** [comment]
Website is up but still having issues on SSL. Please use non SSL URL atm. Sorry for the inconvenience.
