### ISSUE TITLE
It would be awesome to have support for https://editor.datatables.net/

### ISSUE THREAD

**Issue by jackfruh** [yajra/laravel-datatables#113]
I've been messing around with datatables for a day or two- it looks like they offer an editor package that allows for inline editing. It would be really awesome to have support for that in Laravel-Datatables!

**Comment by yajra** [comment]
editor is a paid library and I'm not quite sure if it's ok to support or imitate it's functionality. But I do agree that it would be awesome if we can support it.

**Comment by kirkpatrick** [comment]
If you look at the comments from Datatables Editor they seem to expect people to write integration code so I'm sure it's ok to extend your package to support it.
https://www.datatables.net/forums/discussion/16705/i-have-purchased-editor-but-i-can-t-integrate-it-with-laravel-can-i-do-that-by-backbone

Here is the specs for ajax client / server communication:
http://editor.datatables.net/manual/server

It would be a big plus to use Laravel's form validation and ORM instead of the provided generic php version that they Datatables Editor includes.

**Comment by yajra** [comment]
@kirkpatrick, Sorry, overlooked this one. Thanks for the links will try to give this a shot. However, I don't have a premium copy of the editor library but I think the trial download is full featured. I just hope I will be able to understand and integrate it until it expires. ^_^.

**Comment by robgeorgeuk** [comment]
@yajra Big +1 from me for this feature. I have editor and found the creator (Allan) to be super helpful so *maybe* he'd extend the trial for you (if needed) as this package would be helpful to his customers too.

**Comment by kirkpatrick** [comment]
I wrote an datatables editor module that complements Yajra's. It uses Laravel's existing Validation class. I don't have time right now to publish it... Perhaps next week? Contact me directly if interested.

**Comment by basementjack** [comment]
John, that'd be awesome!

**Comment by yajra** [comment]
@robgeorgeuk, I just remembered that I already downloaded the editor way way back and my copy already expired. Will try to contact Allan and will ask if I can get my copy extended.

@kirkpatrick, I'm interested on your module too. Will be waiting for your release.

**Comment by Razorsheep** [comment]
Any news on this topic? It would be very helpful with an implementation of the editor module in your already great project Yajra! :
+1:

**Comment by kirkpatrick** [comment]
It should be ready tomorrow or Friday. Sorry for the delays
http://datatables.CodeToWeb.com/

**Comment by kirkpatrick** [comment]
Sorry for the delays... It is now live. http://datatables.CodeToWeb.com
This is my first open source contribution. 
Comments are DEFINITELY appreciated.

Thanks

**Comment by basementjack** [comment]
John, this is AWESOME! It may be a bit before I can try it out, but it will definitely come in handy!
A huge THANK YOU for this work!

**Comment by yajra** [comment]
Closing issue since John was able to do the package to support editor. BIG THANKS John!

**Comment by karmendra** [comment]
@kirkpatrick Thanks for your plugin but it is not using Yajra really. When I use yajra I define the entire table in Laravel Controller and $html->script() automatically generates the required Javascript. I wish to editor js is automatically generated as well. that said When I try to use the generated datatable script from $html->script() and define editor and buttons it is not really working together, editor definition is not able to recognize the datatable instance.

@yajra is there something else for laravel datatable editor?

Thanks.

**Comment by vrajeshdoshi** [comment]
@ John Kirkpatrick, I am using your package in Laravel 5.4. I am getting an error "Attribute [controller] does not exist." because of 
    Route::controller('datatables', 'DatatablesController', [
        'anyData'  => 'datatables.data',
        'getIndex' => 'datatables'
    ]);
Can you please do the necessary modifications in the code and commit it on github, as per the latest version of laravel i.e. 5.4 and upcoming 5.5. Great thanks to you, in advance for providing such a wonderful solution.
