### ISSUE TITLE
[SOLVED]Ajax Error , using artisan and Homstead.

### ISSUE THREAD

**Issue by bobbyrinaldy** [yajra/laravel-datatables#1146]
Hay, soory for this question.

i know, someone already ask about it, but they solve within use Homestead instead using 

> Artisan Serve

Beside, I have different error with them, the other geeting error Not found.

Normally my ajax response like this,

![normal](https://cloud.githubusercontent.com/assets/27556560/26042631/2d6724be-3961-11e7-9cbf-f91dad3fb7a0.PNG)

but my Ajax Respon sometime just like this

![ajax](https://cloud.githubusercontent.com/assets/27556560/26042583/dc1de9da-3960-11e7-89f7-9ce5c1ebeb54.PNG)

and this is what console response

![error](https://cloud.githubusercontent.com/assets/27556560/26042707/a1b1beec-3961-11e7-8270-9f106645fa4b.PNG)

**UPDATE**
Just dont use Name on Jquery , just like this ;

Before ;

  ```
columns : [
        {data : 'name' , name: 'name'},
      ],

```

After ;
```
  columns : [
        {data : 'name'},
      ],
```

**Comment by DMeganoski** [comment]
Even though it seems you solved the issue, there are some things you seem to be misunderstanding here and I'd like to point out.

First, artisan serve is part of the core laravel package. it is more intended to use to deploy the site locally, when you don't have apache or nginx available. Homestead comes with nginx, I would personally suggest using that instead of artisan serve. https://laravel.com/docs/5.4/homestead#configuring-homestead

Secondly, neither of those screenshots show any information that could indicate what the issue is. You were almost there in the first screenshot. You were looking at the raw code for the response, which is the raw html and css for the 'oops' page. Had you clicked one tab over to 'preview' it would have rendered the html, while 'response' just show the raw response. This would have more than likely gave you the error description you needed to figure out what's going wrong.

**Comment by bobbyrinaldy** [comment]
@DMeganoski allright, that make sense now. thanks for giving me that information, thats really usefull information that i dont know before.

but , yajra says that some people have an problem if they using artisan , because artisan really slow read css or js that make datatables error to get data.

**Comment by yajra** [comment]
@bobbyrinaldy honestly, I'm not really sure what's causing the error using artisan serve and I just always suggest to move away from it if possible. Thanks! ^_^
