### ISSUE TITLE
Search on mutator

### ISSUE THREAD

**Issue by vanrijs** [yajra/laravel-datatables#1173]
### Summary of problem or feature request

Hi,
Im trying to shorten my code and was wondering if there is a way to search on a mutator. My address column is a concat of: street, number, addition, zipcode, street. 
I want to avoid code like:

```php
            ->filterColumn('address', function($query, $keyword) {
                $query->orWhere('street', 'like', '%'. $keyword . '%');
                $query->orWhere('number', 'like', '%'. $keyword . '%');
                $query->orWhere('number_addition', 'like', '%'. $keyword . '%');
                $query->orWhere('zipcode', 'like', '%'. $keyword . '%');
                $query->orWhere('city', 'like', '%'. $keyword . '%');
            })
```
Datatables columns:
```php
                        columns: [
                            { data: 'id'},
                            { data: 'type'},
                            { data: 'lead', name: 'lead.id'},
                            { data: 'intermediair', name: 'intermediair.email'},
                            { data: 'name', searchable: false},
                            { data: 'address', name: 'full_address'},
                            { data: 'report'},
                            { data: 'authorization'},
                            { data: 'created_at'}
                        ],
```
My mutator:
```php
    public function getFullAddressAttribute()
    {
        return implode(' ', array($this->street, $this->number, $this->number_addition, $this->zipcode, $this->city));
    }
```
I show the address like:
```php
            ->addColumn('address', function ($inspection) {
                return $inspection->full_address;
            })
```
So i use here my mutator: full_address. 

Is there a way to simply search on this mutator? 

- Operating System: Laravel
- PHP Version 5.6.4
- Laravel Version: Master
- Laravel-Datatables Version: 7.*

**Comment by yajra** [comment]
@vanrijs unfortunately, there is no easy way to search on mutator since that field is not part of the query/table. What you implemented is the way I would go about it too. 

Alternatively, you can also do something like below if you don't like filterColumn. Just add a hidden column and it will be included by default on global search.

```js
{ data: 'address', name: 'address', searchable: false},
{ data: 'street', name: 'street', visible: false},
{ data: 'number', name: 'number', visible: false},
...
```

Another way is to create a view or do the column concatenation on SQL level.

**Comment by yajra** [comment]
BTW, since this [multi-term feature](https://github.com/yajra/laravel-datatables/pull/1113). I think you can just add a multiple hidden address fields and the package will search on all those fields. No need to use filterColumn I guess.

On the other hand, I think there is a side-effect on that feature where keyword that being passed to filterColumn are now in multiple terms. I think we should use the whole keyword instead of the exploded terms.
