### ISSUE TITLE
Multiple datatables on one table

### ISSUE THREAD

**Issue by maple9991** [yajra/laravel-datatables#1183]
### Summary of problem or feature request
Hello everyone,
I just started to learn laravel and yajra datatables and I'm new in here.
I'm trying to output two datatables on one table. for one table.
The thing is I can't find anywhere about this issue and I have no clue how I can do.
Do I have to call 'addColumn' function for all columns of them?
I need your help. Please help me. 
Thanks.

![image](https://cloud.githubusercontent.com/assets/25544960/26686315/1fdff52a-471f-11e7-8feb-b85414951229.png)

![image](https://cloud.githubusercontent.com/assets/25544960/26691449/b3c5307e-472f-11e7-8c53-eda188896ece.png)

### System details

- Operating System
- PHP Version 7.0
- Laravel Version 5.4
- Laravel-Datatables Version 7.0

**Comment by DMeganoski** [comment]
*Two database tables into one datatable* Is what you were going for there, I think. 

You seem to be confused about some data relation concepts. Could you also post the `primary` and `building` relation function in your `Account` model? The type of relationships these are are important and would increase your chances of getting a solution.

**Comment by maple9991** [comment]
![image](https://cloud.githubusercontent.com/assets/25544960/26706353/4e1ee734-476f-11e7-84b4-3330765d48a1.png)
![image](https://cloud.githubusercontent.com/assets/25544960/26706368/6a4e84aa-476f-11e7-88b7-305bd8e09a41.png)

As you can see above shown images I've done manually and it worked.
But it is not proper way to do I guess.
Thanks.

**Comment by DMeganoski** [comment]
You are defining that each account has *many* buildings and *many* primaries. Is this the case? I would assume 'primary' would be something there is only one of.

If an account does have many buildings and many primaries, you are only displaying information for the *first* one of many.

If an account only has one primary, I would suggest changing the relationship method to `hasOne()`. It will return the single record instead of a collection with only one item. Then you wouldn't need the `[0]` index.

Here is the documentation on relationships with this package: https://yajrabox.com/docs/laravel-datatables/master/relationships

There would be no easy way to do automatically what you are trying to do here. I would suggest one of two things... if there are many, create a nice html format to display them and put them all in one column. That would require only one `addColumn()` call.

The second approach could be to create [accesors](http://laraveldaily.com/why-use-appends-with-accessors-in-eloquent/) on the account model for each of these fields, then define these fields in the model's `$appends` array property.

**Comment by maple9991** [comment]
Thanks DMeganoski.

And I tried as shown as below. 

![image](https://cloud.githubusercontent.com/assets/25544960/26753078/1094c2da-4891-11e7-9873-11cacf2f89fd.png)

Anyway it works. :)
