### ISSUE TITLE
[SURVEY][V8] DataTables MAJOR BREAKING CHANGES

### ISSUE THREAD

**Issue by yajra** [yajra/laravel-datatables#1246]
Hi Guys,

I will change the namespace of the package from `Datatables` to `DataTables` as I feel it is the right name but it will be a **MAJOR BREAKING CHANGE** for all the users. `Datatables` was used in the beginning since it was inherited from the original package. 

Would you mind sharing your thoughts on the changes I've been working on version 8? All breaking changes are documented on master branch [change log](https://github.com/yajra/laravel-datatables/blob/master/CHANGELOG.md) but I may be overdoing it without taking the users impression on it.

Feedbacks highly appreciated.

Thanks!

**Comment by yajra** [comment]
Draft upgrade guide [docs](https://yajrabox.com/docs/laravel-datatables/master/upgrade) added.

**Comment by AdrianKuriata** [comment]
I don't see anywhere but i think will be good add this attributes to searching.

[data-order attribute](https://datatables.net/examples/advanced_init/html5-data-attributes.html)

Sometimes we want order some field diffrent like a getting data. Maybe this is possible? I don't saw this possibility.

**Comment by yajra** [comment]
@AdrianKuriata thanks for the input. You can already implement the same feature now but on a `server-side` way.

For `data-search`, you can have both `first_name` and `last_name` included on search by adding a hidden column and display the formatted name using `addColumn` or via mutator. Same goes for order part.

```js
columns: [
  {data: 'name', name: 'last_name'},
  {data: 'first_name', visible: false}
]

**Comment by yajra** [comment]
Sure, please create a new issue for a new thread.

**Comment by AdrianKuriata** [comment]
I created it, #1244 .

**Comment by AdrianKuriata** [comment]
@yajra Hi Yajra. I tested up your solution for searching with other fields which is not visible.

1. When i did it, in `print`,` copy to clipboard` and `csv` file i see this field. When i added printable and exportable on false this not working. In the `D` section you can see field which is `visible` on `false` and `printable`, `exportable` on `false`. [Pic](http://i.imgur.com/k5VDRit.png).
2. With this solution i can't use few field to search, let me explain. I have 3 models, `Street`, `Floor`, and `Flat`. I want add this to the search like a connected one field (ex. `Wall Street 3/1` where in `Street` model is `Wall Street` etc. in `Floor` is `3` etc. and `Flat` is `1` etc.). With your solution i can create couple fields with separated information about street. I tested `date`. When i have `date` saved like a timestamp in the database i can't search with her using converted `date` to format like a `d.m.Y`. This is because `name` field working with database, i can't set custom values with searching. When i changed it with `editColumn` this won't work, i can just searching with timestamp format. With `data-order` and `data-search` i can put formated date and searching will be working properly. When i don't add `name` field(`name` working like that, when you don't add `name` field, this will extend data from `data` field, i thought this will work when i convert data in `editColumn`, but this won't work. I know i can create custom search engine and use filtering, but solution with data-attribute would be really usefull.

**Comment by OzanKurt** [comment]
I think that the namespace should definitely be `DataTables`. It's nice to see you working on this. I will contribute more about laravel routing/filtering stuff after I get free from the current projects I have.

Thanks!
