### ISSUE TITLE
Is there a default limit on any json feed url with no GET filter attributes.

### ISSUE THREAD

**Issue by grafxflow** [yajra/laravel-datatables#1264]
Basic question on a default limit on any json feed.

So for example if using pagination on something like 'api/v1/viewJsonFeed?length=10' it brings back the 10 records out of 700+.

`api/v1/viewJsonFeed?length=10`

But if I use 'api/v1/viewJsonFeed' it returns the full 700+. Is there anyway to set a default limit as a fallback setting.

`api/v1/viewJsonFeed`

**Comment by yajra** [comment]
There is no default limit on length since the value is submitted by the frontend dataTables.js library when creating the request.

On the other hand, I think you are using the package on a different way? The only way I can think of to set the default value is via middleware. Just merge a default limit value on request instance if none is set.

```php
if (!request()->has('limit')) {
  request()->merge(['limit' => 10]);
}
```
