### ISSUE TITLE
Click on export button giving error

### ISSUE THREAD

**Issue by rathiatul25** [yajra/laravel-datatables#1371]
### Summary of problem or feature request

When I click on export button, I am able to download excel, pdf etc. But when I click on anywhere on window, option aren't disappearing and getting error below-
e(...).parents(...).andSelf is not a function

### System details

- Ubuntu 16.04
- php 5.6
- Laravel 5.4
- Laravel-Datatables 7.0

**Comment by yajra** [comment]
Can you please provide some snippets to reproduce the issue?

**Comment by jdkoelsch** [comment]
I think the issue is that this script tries to use andSelf(): 
https://cdn.datatables.net/buttons/1.0.3/js/dataTables.buttons.js

jQuery removed andSelf() in v3, according to this: https://stackoverflow.com/questions/40771508/jquery-3-1-1-error-object-doesnt-support-property-or-method-andself

The Basic Service Implementation example on this site is still using jQuery v2.1.3, so its not causing an issue.

**Comment by yajra** [comment]
@jdkoelsch thanks for the inputs. I think that is indeed the issue where assets versions are conflicting. 👍

**Comment by rathiatul25** [comment]
@jdkoelsch Thanks for reply. I have replaced the function and its working fine.
