### ISSUE TITLE
Performance issues when using Blade templating on ->editColumn()

### ISSUE THREAD

**Issue by Arkhas** [yajra/laravel-datatables#1534]
### Summary of problem or feature request

When using the blade synthax instead of a closure inside the `->editColumn()` or `->addColumn()` function, when displaying like 250 results instead of 25, the loading time of the XHR is longer.
(In our tests, 7s(blade) vs 800ms(closure))
### Code snippet of problem

```php
->editColumn('boolean',  '{{ $formation->boolean ? "YES" : "NO" }}')
```

VS 

```php

->editColumn('boolean', function ($object) {
                return $object->boolean ? "YES" : "NO";
            })
```

### System details

- Operating System
Debian wheezy
- PHP Version
PHP 7.1.8
- Laravel Version
Laravel Framework 5.5.19
- Laravel-Datatables Version

```
yajra/laravel-datatables-buttons      v3.1.0             Laravel DataTables Buttons Plugin.
yajra/laravel-datatables-html         v3.2.1             Laravel DataTables HTML builder plugin for Laravel 5.4+.
yajra/laravel-datatables-oracle       v8.3.2             jQuery DataTables API for Laravel 4|5
```

**Comment by HadrienKulik** [comment]
Just to clarify, this seems to have a **major** impact, even on fairly small datasets. 

On a table with just 250 rows, that has 20 columns, if 5 of the columns are formatted using some blade syntax inside an `editColumn`, it loads the set in 3.5 sec, while doing the same formatting in closure allows to do it under 1 sec. So just going through these 250 x 5 = 1250 cells seems to take 2.5 additional seconds when doing `{{ $formation->boolean ? "YES" : "NO" }}` vs. `function ($object) { return $object->boolean ? "YES" : "NO"; }` 😲 

The problem is that it is easy to replace some blade syntaxes with closures, but sometimes we have some more complex `editColumn` such as progress bars, etc. which are way better handled inside a `.blade.php` file.

@yajra Do you think there is any way to improve perf on that front, or it is just the way it is by design?

I noticed that the views seem to be called as many time as there are cells calling them :
![image](https://user-images.githubusercontent.com/1494897/33588674-0e6ee2d2-d942-11e7-82bc-71e41985706b.png)
Are they actually loaded at every blade cell, or is there some caching involved (at a row, column, or table level) ?
