### ISSUE TITLE
Possibility to use HAVING instead of WHERE everywhere

### ISSUE THREAD

**Issue by royduin** [yajra/laravel-datatables#1598]
I let my users create their own subqueries which can be used as columns in the table. But wheres are not working with values from subqueries so I need havings for example [here](https://github.com/yajra/laravel-datatables/blob/8.0/src/QueryDataTable.php#L404) to get the search working.

Any plans to integrate this possibility? Maybe as a global config or as a option which can be set through the constructor of the QueryDataTable class?

**Comment by yajra** [comment]
Not sure on this. I think I tried using having queries way back and I found it buggy / not working well with where sql. I think it may work sometimes on mysql but not on other db like Oracle? Or I might be using it wrong, not sure.

But anyways, if you can propose a PR to support it then I guess we can add it. I may not have time yet to add this due to some projects on hand. Thanks!

**Comment by royduin** [comment]
For now I've wrapped the query in a query with:
```
$query = DB::table(DB::raw("({$query->toSql()}) as t"))->mergeBindings($query);
```

That's working with where's, but the performance isn't that great. If I find myself some time I'll try to create a PR for this.
