### ISSUE TITLE
Website does not work

### ISSUE THREAD

**Issue by cromartie1984** [yajra/laravel-datatables#1618]
https://yajrabox.com/docs/laravel-datatables -> something went wrong

**Comment by unalgo** [comment]
I can confirm the issue with documentation website. It's not working.

**Comment by sagarpatel9697** [comment]
yes I am looking for documentation, but it gives an error since an hour.

For [https://yajrabox.com/docs/laravel-datatables](https://yajrabox.com/docs/laravel-datatables) page

![datatable_1](https://user-images.githubusercontent.com/25764632/36025896-c09b6bfe-0dba-11e8-8220-6352847ff026.png)

For [Laravel 5.4 Demo Application](http://dt54.yajrabox.com/) page 

![datatable_2](https://user-images.githubusercontent.com/25764632/36025954-fcab5924-0dba-11e8-8727-c1084a87e3dd.png)

**Comment by yajra** [comment]
Fixed, thanks!
