### ISSUE TITLE
Search in edited/added columns

### ISSUE THREAD

**Issue by EdisonLV** [yajra/laravel-datatables#168]
It seems that if I add or edit column(s) datatables does not perform search on these columns...
```php
      return Datatables::of($listings)
          ->editColumn('price', '$ {{ money_format("%i", $price) }}')
          ->editColumn('created_at', '{!! $created_at->diffForHumans() !!}')
          ->editColumn('updated_at', '{!! $updated_at->diffForHumans() !!}')
          ->addColumn('title', function ($listing) {
              return $listing->title;
          })
          ->make(true);
  }
```

**Comment by ChaosPower** [comment]
Hi @EdisonLV,

editColumn is in a different scope than what you wanted.

editColumn only edit's the output. You have to find a way to let Datatables know in SQL scope of what it needs to search for.

I would suggest using transformers instead of editColumn method. This way Datatables SQL scope would know how to represent the transformed data because it now has a reference of the proper column it needs to sort / search and etc.

http://datatables.yajrabox.com/eloquent/transformer

**Comment by yajra** [comment]
@EdisonLV, search/sort via added column is not possible because it's not part of the query. If you want to make it searchable, then add it using query builder like `addSelect("'my title' as title")`. For searching on edited columns, you may have to write a custom query to fully search on it's edited value.

On other hand, try using collection by using `$listings->get()`. However, there is a downside here because all data will be loaded at once and may cause performance issue when your DB becomes large.

**Comment by yajra** [comment]
Basically, the edited/added columns are not part of the query so searching on it's new value is not possible using normal SQL query which makes it not possible for the package to do so.
