### ISSUE TITLE
Column Filtering with Dropdown

### ISSUE THREAD

**Issue by oranges13** [yajra/laravel-datatables#1690]
This is a great plug in and it is working well, but I am running up against an issue that I haven't been able to figure out.

I have successfully implemented column filtering as shown in this example: 
https://datatables.yajrabox.com/eloquent/post-column-search

But I would like to use select boxes as shown here: https://datatables.net/examples/api/multi_filter_select.html

The issue is that the select boxes only show the data available on the first visible page of the table, not all available options. Any suggestions on how to return the options for each column from the plugin?

Here's my initComplete that creates dropdowns:

```javascript
initComplete: function () {
	this.api().columns([0,2,3]).every( function () {
		var column = this;
		var select = $('<select class="form-control"><option value=""></option></select>')
			.appendTo( $(column.footer()).empty() )
			.on( 'change', function () {
				var val = $(this).val();
				column.search( this.value ).draw();
			} );
		// Only shows the *visible* options
		console.log(column.data().unique());

		// How can I access all column options here from the server side?
		column.data().unique().sort().each( function ( d, j ) {
			select.append( '<option value="'+d+'">'+d+'</option>' )
		} );
	} );
}
```

**Comment by yajra** [comment]
I think this needs more work than the example since it's only applicable on client-side as seen on your output. 

First, we need to fetch all the unique records in our database per column. We then need to bind this collection on our view and create a script that will loop on each value per column. 

I don't have any snippet for this but that is how I see implementing this.
