### ISSUE TITLE
Need help on addcolumn html rendering

### ISSUE THREAD

**Issue by onlinecheckwriter-zz** [yajra/laravel-datatables#1726]
Hello,
We are using the following code : 
```
    return Datatables::of($users)
            ->editColumn('created_at','theme.test')-> make(true);
```

_View file (theme.test)_
```
10/20/30 <b>10:320PM</b>
```

it is coming as `10/20/30 <b>10:320PM</b>` instead of coming 10/20/30 **10:320PM** on datatable.

**Comment by drbyte** [comment]
Something doesn't seem to have come through clearly in your post.

If you were including HTML markup, it's been rendered instead of posted literally.
Perhaps add a backtick (`) before and after the "code" so that your post can be understood more clearly?  (or click the **Insert Code <>** button in the button bar to do it for you, and stick your "code" inside the backticks that are displayed.)

**Comment by Skintillion** [comment]
Have you tried adding `->raw('created_at') `

**Comment by Skintillion** [comment]
What is in your theme.test file?

**Comment by yajra** [comment]
You need to use `rawColumns` for any fields that have html contents.

```php
return Datatables::of($users)
            ->editColumn('created_at','theme.test')
   ->rawColumns(['created_at', ...])
   -> make(true);
```

**Comment by onlinecheckwriter** [comment]
Thank you
