### ISSUE TITLE
snappy not work with export pdf

### ISSUE THREAD

**Issue by mohamed0000** [yajra/laravel-datatables#1751]
The exit status code '1' says something went wrong:\n
stderr: "The system cannot find the path specified.\r\n
"\n
stdout: ""\n
command: /vendor/h4cc/wkhtmltopdf-i386/bin/wkhtmltopdf-i386 --lowquality --margin-bottom "10mm" --margin-left "0" --margin-right "0" --margin-top "10mm" --orientation "landscape" --no-outline "C:\Users\Mohamed\AppData\Local\Temp\knp_snappy5b0bd2dc883b85.15670891.html" "C:\Users\Mohamed\AppData\Local\Temp\knp_snappy5b0bd2dc9a0e45.72948721.pdf"

**Comment by yajra** [comment]
Maybe try installing wkhtmltopdf binary instead. For further info, I suggest you check on snappy repo. Thanks!

**Comment by LexxLuey** [comment]
I still experienced this error of recent... any known solution>

**Comment by indrysfa** [comment]
I also have an error like this, can you help?

**Comment by patian** [comment]
I just got similiar error. In my case i install linux version of h4cc/wkhtmltopdf on windows system. And i using the binary version. The error means composer can't find the specific package. First check your system is window or linux, on my case i using windows so i use wemersonjanuario/wkhtmltopdf-windows instead. If you using linux then stick with h4cc/wkhtmltopdf. Then what system bit you using is 32bit or 64bit, you must install correctly. Lastly setting the snappy configuration, because i using laravel framework so i edit in App\Config\Snappy.php

```
<?php

return [
'pdf' => [
        'enabled' => true,
        'binary'  => env('WKHTML_PDF_BINARY', base_path('vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltopdf.exe'),),
        'timeout' => false,
        'options' => [
            'enable-local-file-access' => true,
            'print-media-type' => true
        ],
        'env'     => [],
    ],
'image' => [
        'enabled' => true,
        'binary'  => env('WKHTML_PDF_BINARY', base_path('vendor/wemersonjanuario/wkhtmltopdf-windows/bin/64bit/wkhtmltoimage.exe'),),
        'timeout' => false,
        'options' => [
            'enable-local-file-access' => true
        ],
        'env'     => [],
    ],
];
```
The pdf and image binary is depend where your package located. 
Hopefully can help
