### ISSUE TITLE
How to modify the query that counts everything in the table ?

### ISSUE THREAD

**Issue by Al3xR0** [yajra/laravel-datatables#188]
I am doing 2 left joins on a database with 200.000 rows. I want to modify the first query with select count(*) to not include the left joins, so that it will be more faster. The values from the joins are not searchable in the table.

The queries generate by datatables are this:

select count(*) as aggregate from ... -> 1.55 seconds
select ... from ... -> 1.86 seconds

**Comment by yajra** [comment]
@Al3xR0, Sorry! As far as I know, there is no way of overriding the count query. And `select count(*) as aggregate from ...` was the default query generated by Laravel. 

BTW, since the joins are not searchable then maybe eager loading may work? This way, only the primary table will be used on count query. Though I am not sure if performance would be better on eager loading.

**Comment by Al3xR0** [comment]
I used relations queries and attributes and now the counting query is much better. Thanks :+1:

**Comment by yajra** [comment]
:+1:
