### ISSUE TITLE
Belongs To Eager Loading Soft Deleted: withTrashed() is ignored when sorting

### ISSUE THREAD

**Issue by FilipQL** [yajra/laravel-datatables#1888]
### Summary & Code snippet of problem or feature request

There are 2 Eloquent models with the following relationship:

- `Post` _belongsTo_ `Thread`

Thread can be soft-deleted (https://laravel.com/docs/5.7/eloquent#soft-deleting).

I am using Datatables to display **posts**. I "_eager load_" **threads** (similarly to [your example](https://datatables.yajrabox.com/relation/belongs-to)), but because threads can be soft-deleted - I had to add `withTrashed()`:

```
        $posts = Post::select('posts.*')
            ->with(['thread' => function ($query) {
                $query->withTrashed();
            }]);
```
... to avoid errors. And everything works fine, `'thread.title'` column is there and the _posts_ that belong to the soft-deleted _threads_ are also listed. 

But when I try to sort by the `'thread.title'` column - `withTrashed() ` is ignored and Datatables shows only _posts_ that belong to _threads_ that have **not** been deleted (but it still counts all the posts including those that belong to _threads_ have been deleted).

--------------------------------------

For example, lets say that there are **9** _posts_ stored in the DB (in `posts` table), of which **2** belong to _thread_ that has been soft-deleted. Datatables will show **all 9 posts**, and at the bottom there will be:

```
Showing 1 to 9 of 9 entries
```
Then I click on the `'thread.title'` column to order by the thread titles and Datatables will show **7 posts** (that belong to _threads_ that have **not** been deleted). The remaining 2 posts that belong to thread that has been deleted are not shown (loaded) anymore. 
But it will still show:
```
Showing 1 to 9 of 9 entries
```
at the bottom.

--------------------------------------

- Initially, these queries are executed:

```
select count(*) as aggregate from (select '1' as `row_count` from `posts`) count_row_table // 9
select `posts`.* from `posts` order by `id` desc limit 10 offset 0
select * from `threads` where `threads`.`id` in ('1', '2', '3') // '3' has been soft-deleted
```
   ... and all 9 posts were displayed ( including two belonging to the soft-deleted thread).

- After sorting by the `'thread.title'` column:

```
select count(*) as aggregate from (select '1' as `row_count` from `posts`) count_row_table // 9
select `posts`.* from `posts` left join `threads` on `posts`.`thread_id` = `threads`.`id` where `threads`.`deleted_at` is null order by `threads`.`title` asc limit 10 offset 0 // `withTrashed()` is ignored and "where `threads`.`deleted_at` is null" was added
select * from `threads` where `threads`.`id` in ('1', '2') // '3' is not specified anymore (like initially was) because `withTrashed()` is ignored
```
... only 7 posts were displayed (that belong to _threads_ that have **not** been soft-deleted). But it will still display "Showing 1 to 9 of 9 entries"...

--------------------------------------

### System details

- Operating System: Windows 7 64 bit
- PHP Version: 7.2 (XAMPP)
- Laravel Version: 5.6.39
- Laravel-Datatables Version: 8.9.1

**Comment by FilipQL** [comment]
@yajra I just tried suggested workaround and it did not work, `withTrashed()` is sill being ignored **after** sorting by the `'thread.title'` column (the same as I described above).

```
    public function thread()
    {
        return $this->belongsTo(Thread::class)->withTrashed();
    }
```

**Comment by selecod** [comment]
@yajra withTrashed() method is ignored, aswell as onlyTrashed()
That's happens due to [1628](https://github.com/yajra/laravel-datatables/pull/1628/commits/2156787cc12995ed0d94ef40c6b3c2920fef1b48#diff-d7663255b88a6aed388d85442e3ec2e0R216) PR

In EloquentDataTable at the end of **performJoin** method we have 
`if ($deletedAt !== false) {
$this->getBaseQueryBuilder()->whereNull($deletedAt);
}`

`$deletedAt` variable always has value with a field name if related model using SoftDelete. No matter what kind or relation is set.

So the problem is:
- It works well when we don't want to have deleted records in results
- If model relation is set with `withTrashed()`, `$deletedAt` in not `false` and we applying `->whereNull($deletedAt)`, but we **shouldn't**
- If model relation is set with `onlyTrashed()` we still got `$deletedAt` with field name and applying `->whereNull($deletedAt)` instead of **`->whereNotNull($deletedAt)`**

This happens only with joining tables, not with counting records. That's why total records not equals to displayed results sometimes.

I've tried to remove this whole comparison part with `$deletedAt`. Relations with `withTrashed()` and `onlyTrashed()` works like a charm and just like they should to. Tested with Laravel 5.5 and Laravel-Datatables v8.13.6. Queries in Debugbar were correct.

Since as from v8.0.0 we got 
`On the fly support for SoftDeletes. No need to use withTrashed and onlyTrashed.`
I think this part of a code looks redundant and should be removed.

Same issue with #1692

**Comment by yajra** [comment]
@selecod can you please submit a PR on the solution you've mentioned. Will try to check it as soon as I can. Thanks!

**Comment by selecod** [comment]
@yajra sure, here it is
#2103

The same can be applied to 9.0 branch, if everything is fine.
