### ISSUE TITLE
Nested Resource Collections includes eloquent object

### ISSUE THREAD

**Issue by swilla** [yajra/laravel-datatables#1967]
### Summary of problem or feature request

When included an embedded resource collection, the array is nested in an object:

![screen shot 2019-01-23 at 3 48 53 pm](https://user-images.githubusercontent.com/304159/51636108-6aa61b80-1f26-11e9-894b-9ccc0bbf0630.png)

I would expect the `groups` attribute to contain null, or an empty data array. The formatting works fine on the parent resource. 

### Code snippet of problem

The Parent resource:
```php
return [
            'id' => (int) $this->id,
            'title' => $this->title,
            'groups'=> GroupResource::collection($this->whenLoaded('groups')),
        ];
```

The Group resource is as follows: 
```php
    /**
     * Transform the resource into an array.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return array
     */
    public function toArray($request)
    {
        return [
            'id' => (int) $this->id,
            'name' => (string) $this->description,
        ];
    }
```
### System details

- Operating System: macOS 10.14.2
- PHP Version: 7.3.1
- Laravel Version: 5.7.19
- Laravel-Datatables Version: 1.10.19

**Comment by yajra** [comment]
I haven't tried resource that much but based on the code, it seems like `'groups'=> GroupResource::collection($this->whenLoaded('groups')),` returns a new class that is converted to array. Maybe a `??` can be added to catch empty class?

```php
'groups'=> GroupResource::collection($this->whenLoaded('groups')) ?? [],
```

**Comment by DrLongGhost** [comment]
Here's some feedback on broken behavior I noticed and a few suggestions for improving stuff. Feel free to disregard, as needed.

* The Pairs page is broken: Error on http://localhost:8888/pairs -- Call to undefined method App\Models\Bluetoad\Device::devices(). It might be a little tricky to keep all parts of the other 2 CRUD pages working while advancing this ticket, since this could well be an involved breaking change. So if we don't want to try and update all 3 pages at once and get everything perfect in one go, I'm not opposed to breaking Pairs and Routes temporarily while we work though this, as unfortunate as that might be.
* When using the new Group picker, is it possible to remove the "Press enter to select" text? It obscures the group name of the currently active selection, making the picker more difficult to use. (Alternately, giving the Group picker its own line in the layout, making it 4 times wider, would also fix the issue).
* Can we customized the message shown when no Group is selected? "Select a Group" or "You must select a Group" is preferable to "Pick some".
* When adding a new Device, perhaps the Groups selector should prepopulate with all groups the user currently belongs to? Certainly if they only belong to one group, it should prepopulate with that one. If they belong to multiple groups, I can see the argument for leaving it empty and making them manually pick one.
* Trying to add a new Device throws the following Error: "{
    "message": "Call to a member function update() on null",
    "exception": "Symfony\\Component\\Debug\\Exception\\FatalThrowableError",
    "file": "/var/www/html/app/Http/Controllers/Api/ApiDeviceController.php",
    "line": 82,"
* You don't appear to be filtering the list by groups that the user has access to. I went into the "og_uid" table and deleted user_id 1's access to about half the groups. The select box continued to show those groups as valid selections.
* Also relevant to the point above is the use case scenario I had previously mentioned to you in chat. User A puts a device in Groups A and B. User B belongs to Groups B and C. He opens the device and should not see any mention of Group A (since he doesn't have access to it). He saves it to Group B and C, so now it should be in Groups A, B and C and the Group A ownership should not have been overwritten

**Comment by ehsanrasta** [comment]
same problem

**Comment by sanshan** [comment]
same problem
