### ISSUE TITLE
Why is there a queries data object?

### ISSUE THREAD

**Issue by TechKat** [yajra/laravel-datatables#231]
What is the need for it? Huge security issue there.

**Comment by yajra** [comment]
It's for debugging purposes. Just disable debug mode and it should be gone. 

Sent from Outlook using iPhone




On Sat, Oct 31, 2015 at 12:43 AM -0700, "Craig McKie" <notifications@github.com> wrote:












What is the need for it? Huge security issue there.

**Comment by TechKat** [comment]
Is this mentioned anywhere in docs? Because I probably missed it.

**Comment by yajra** [comment]
Hmm. Not really sure if I was able to document it but there was some issue raised like this as far as I remember. This debug feature is available since the project was forked from original version of Bllim. 
Anyways, will add this on documentation on my free time. Thanks!


Sent from Outlook using iPhone




On Sat, Oct 31, 2015 at 5:03 AM -0700, "Craig McKie" <notifications@github.com> wrote:












Is this mentioned anywhere in docs? Because I probably missed it.

**Comment by yajra** [comment]
Added on read me. Thanks!
