### ISSUE TITLE
Problem Add Column with Closure help

### ISSUE THREAD

**Issue by demaspaa** [yajra/laravel-datatables#2602]
### Summary of problem or feature request

i have a blade template and a function like this to do CRUD, it just doesn't work 

### Code snippet of problem

Blade View : dataaction.blade.php
```
<form action="{{ route('admin.user.destroy', $user->id) }}" method="post">
    @method('DELETE') @csrf
    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
        <a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-info text-white">Edit</a>
        <button type="submit" class="btn btn-danger text-white">Delete</button>
    </div>
</form>
```

Function in Controller
```
public function getDataUser(){
        $users = DB::select('SELECT * FROM roles JOIN role_user ON roles.id = role_user.role_id JOIN users ON users.id = role_user.user_id');
        return Datatables::eloquent($users)
            ->addColumn('fungsi', function(User $user){
                $route = $this->route;
                return view('pages.admin.user.dataaction', compact('route', 'user'));
            })
        ->toJson();
    }
```

### System details

- Operating System = Windows 10
- PHP Version = 7.4.3
- Laravel Version = 8.x
- Laravel-Datatables Version = 8.x

**Comment by schonhoff** [comment]
Hi,

can you show the error message which the current code is generating? 

You are using Datatables::eloquent on an array not on an eloquent query. Maybe that is the error. Although your variable is $user but you are querying the roles as the main table.

Try the following code, if your models have the relationship functions set like the following:

```php
use Yajra\DataTables\Facades\DataTables;

class YourController extends Controller {
  public function getDataUser(){
    return DataTables::eloquent(User::with('roles'))
      ->addColumn('fungsi', function(User $user) {
         $route = $this->route;
         return view('pages.admin.user.dataaction', compact('route', 'user'));
      })
      ->toJson();
  }
}
```
Be carefull to use the right DataTables class and be careful with the camel case.

```php
class User extends Authenticatable {
  [...]
    /**
     * The roles that belong to the user.
     */
    public function roles()
    {
        return $this->belongsToMany(Role::class);
    }
}
```
See here: https://laravel.com/docs/8.x/eloquent-relationships#many-to-many-model-structure

In your CRUD template I would change something too:

```html
<a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-info text-white">Edit</a>
<form action="{{ route('admin.user.destroy', $user->id) }}" method="post">
    @method('DELETE') @csrf
    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
        <button type="submit" class="btn btn-danger text-white">Delete</button>
    </div>
</form>
```
I don't know why you are send a variable ```route``` to the template but I didn't change it. Maybe it is used in another code part that is not presented here. If this is the only part you don't need the route variable at all because ```route()``` is a laravel helper :-)


Also I would suggest you to read the following for CRUD as a nice little clue:
https://laravel.com/docs/8.x/routing#route-model-binding

With the route model binding your form can be this:
```html
<a href="{{ route('admin.users.edit', $user) }}" class="btn btn-info text-white">Edit</a>
<form action="{{ route('admin.users.destroy', $user) }}" method="post">
    @method('DELETE') @csrf
    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
        <button type="submit" class="btn btn-danger text-white">Delete</button>
    </div>
</form>
```

And your controller should have the following change:

```php
public function edit(User $user) {
   [...]
}

public function destroy(User $user) {
   [...]
}
```
With this change you don't need to deal with findOrFail in your CRUD functions anymore.
Just to be completely safe, you would need to use the following in your web.php:

```php
Route::prefix('admin')->group(function () {
  Route::resource('users', 'CONTROLLERNAME');
});
```

Be careful with this change. I changed the admin.user to plural :-)

Hope I could help you. I was writing the same code for a CRUD DataTable today.
