### ISSUE TITLE
Cannot use addRow option in package

### ISSUE THREAD

**Issue by asmafarhat2006** [yajra/laravel-datatables#269]
Hi!
Good work for the package first.

I have been trying to add a new row dynamically using datatable addRow method : https://datatables.net/examples/api/add_row.html

But it doesnt work because draw function invokes the ajax call and the same set of rows is returned again.
Does this package support this function or am i doing something wrong?

**Comment by yajra** [comment]
@asmafarhat2006, You are correct that `draw` method will trigger an ajax call to reload the data. That is how the datatables js works by design. If you want to implement add row, try not calling `draw`. If it does not work, then I guess it's only applicable via client-side and not on the server-side approach.

**Comment by asmafarhat2006** [comment]
@yajra  ok .i thought so.
What about inline editing functions,does this package supports inline-editing?

**Comment by yajra** [comment]
Well I think inline editing is partially supported and possible. However, just avoid doing a refresh or sorting/filtering when on edit mode to avoid redrawing of contents.
