### ISSUE TITLE
Double count queries on v10

### ISSUE THREAD

**Issue by omadijaya** [yajra/laravel-datatables#2884]
### Summary of problem or feature request

Hello there, 
I want to upgrade our `laravel-databales` version from v9 to the latest version,
however after upgrade, we feel like it slower than v9 and after take a look to the query it has double query for count query

![image](https://user-images.githubusercontent.com/83449781/196865945-49b53478-d28a-42f0-b623-a8c42ae840c3.png)

The first and sec query look exactly same for me, Not sure if these are expected ?

### System details

- Operating System : Windows 10 & Ubuntu
- PHP Version : 8.1
- Laravel Version : 9.36.2
- Laravel-Datatables Version : 10.1.6

**Comment by yajra** [comment]
@omadijaya this is actually an expected behavior since the first count is for the total records and the next one is for the total filtered records. However, it was optimized on the previous version but had to be removed to fix several issues. There was a recent PR that attempts to fix this https://github.com/yajra/laravel-datatables/pull/2852 but the tests are failing so I cannot merge it yet.
