### ISSUE TITLE
Datatables Eloquent Triggering count(*) query twice

### ISSUE THREAD

**Issue by geniqtech** [yajra/laravel-datatables#2959]
Updated Datatables to latest version recently but noticed that the behaviour has changed in such a way that count(*) queries are triggered twice?

Example Code:
$response= datatables()->of($query)->toJson();

SQL Queries:
select count(*) as aggregate from (XXX);
select count(*) as aggregate from (XXX);
[Actual SELECT query]

The issue here is that we are dealing for fairly large datasets (in millions) and count(*) statements are quite expensive. Moreover the "XXX" statement is the same for both count(*) queries. 

Is there anyway to prevent this double query?

**Comment by yajra** [comment]
This is an expected behavior that occurs mostly on initial load. The previous version skips the filtered count on the initial load but it causes some issues with some features like `skipPaging, skipTotal, setFilteredRecords, etc` if I recall correctly.

I will try to revisit the implementation as this is an issue that I think is raised several times now.

**Comment by Arne1303** [comment]
@geniqtech We added a cache for the total count to our DataTables that way we have one less request to the database in most cases (Simply overwriting the `count` function does the trick) maybe that also works for you.


@yajra I also thought about writing a PR which gets rid of the second request when searching but its doing what its supposed to do it needs both the total amount and the amount filtered to display it in the UI so I wasn't able to think of a way to get rid of the second request.

The only think I came up with is that if the count of the collection with filtered records is less than the limit to be displayed the count of that collection could be used instead of an other database request. But that does only way in specific situations so I skimmed out of making a PR for it for now until I come up with a better way.

**Comment by yajra** [comment]
What if we make it configurable to something like `skipFilteredCountOnInitialLoad` which takes `draw=1` parameter as the initial load indicator?

**Comment by geniqtech** [comment]
> What if we make it configurable to something like `skipFilteredCountOnInitialLoad` which takes `draw=1` parameter as the initial load indicator?

Yes this seems like a viable option

**Comment by RonaldBrink00** [comment]
For me using `datatables()->eloquent($query)->setTotalRecords($total)` seems to reduce it to 1 query, but it still shows the value of the count query instead of $total. Could this be related to this issue?
