### ISSUE TITLE
Api Columns method with server side processing not working fine

### ISSUE THREAD

**Issue by sangar82** [yajra/laravel-datatables#305]
Hi @yajra !!

I love this package!! Thanks!!

I have a problem with server side processing and a column sum

This is my code:

````js
datatable = $('.datatables').DataTable({
    iDisplayLength: 25,
    processing: true,
    serverSide: true,
    ajax: 'http://www.myroute.com/ajax',
    aaSorting: [[0,'desc']],
    columns: [
        {data: '0', name:'data'},
        {data: '1', name:'sum'},
    ],
});
````

````js
$(document).on('click', '.button_sum', function (e){
    alert( 'Column 1 sum: '+
            datatable.column( 1 )
                    .data()
                    .reduce( function (a,b) {
                        return parseInt(a) + parseInt(b);
                    }));
});
````

If I have more than one page, datatable.column(1).data() only returns the actual page. Without serverside it works perfect. 

If you have more than one page and you click in order filters, sometime I get the correct sum, not only the sum for the actual page.

Can you help me please? I need sum working in footer for server side.

Thanks!!!

**Comment by yajra** [comment]
Hi @sangar82, Api columns works but as you said, it will only return datasets from the actual page and this is expected since we only fetch data per page unlike the client-side version which pulls all data at once.

Anyways, if you want to add a sum on the footer, you can just sum it on controller and just pass it on the view. Or you can passed another variable on datatables json response then append it to dom by listening on `dt.draw` and/or some other events as needed. Follow my proposed work around here if you want to add a new variable from datatables response. https://github.com/yajra/laravel-datatables/issues/277

**Comment by kylesean** [comment]
@yajra It's a good solution.
Could you tell me how to render the additional response data in html,such as:

```
{
    "draw": 1,
    "recordsTotal": 427,
    "recordsFiltered": 427,
    "data": [],
    "total_price": "18240035.89",
    "queries": [],
    "input": {}
}
```
How to get the value of total_price in html or js .Thank you.
