### ISSUE TITLE
Change column name in export and print

### ISSUE THREAD

**Issue by fanjavaid** [yajra/laravel-datatables#310]
Hay all, 

is there any way to change export and print column, not using field database like **credit_no** etc but using **Credit No**

Thank you ^^

**Comment by WesThorburn** [comment]
Could you use SQL aliases in your query? SQL aliases temporarily rename a table or a column heading. 

For example, you could change your query to something like. "<b>SELECT credit_no AS [Credit No];</b>" (You should use square brackets if your alias has a space in it). 

You wouldn't need to worry about changing the column name when you print or export, because the query will already return it in the format that you want. 

There are more examples here: www.w3schools.com/sql/sql_alias.asp

**Comment by yajra** [comment]
I just released v6.2 which enhances the default print and export function to match what is displayed in the UI. Check it out! Thanks!
