### ISSUE TITLE
Two or more data tables simultaneously

### ISSUE THREAD

**Issue by sarfraznawaz2005** [yajra/laravel-datatables#321]
Hi yajra,

I have been having hard time figuring out how to render two data tables at the same time when using as **Service**. I have two bootstrap tabs on page and in each tab I want to show different datatable, I have this:

    // controller
    public function index(MyDatatable1 $dataTable1, MyDatatable2 $dataTable2)
    {
        // how i pass both data tables to be rendered in view ??
      
        return $dataTable1->render('myview');
    }

    // view
    {!! $dataTable->table() !!}

Now as can be seen only one `return` statement can be used, I cannot render another datatable in the same page.

Can you please tell how can we do this when using as service or some other alternative ?

Thanks for your help in advance!

**Comment by yajra** [comment]
@sarfraznawaz2005, You can only pass one DataTable service per method atm. If you need to use multiple tables in a single page, you will have to manually write the js scripts on the other tables. You also have to set the `ajax` property of the others tables to another route. 

```php
public function index(MyDatatable1 $dataTable1)
{
    return $dataTable1->render('myview1');
}

public function table2handler(MyDatatable2 $dataTable2)
{
    return $dataTable1->render('myview1');
}
```

On my `myview1`:
```php
// table1
{!! $dataTable->table() !!}
// add html for table2

// scripts for table 1
{!! $dataTable->scripts() !!}
// add scripts for table2 and set ajax to table2handler
$(table).DataTable({
  ...
  ajax: '/table2handler'
  ...
})
```

**Comment by sarfraznawaz2005** [comment]
okay yes i had this in mind as alternative so going to take this route for now. Thanks for the reply.

**Comment by gredimano** [comment]
Hi Yajra,

I've been encountering problem about rendering 3 datatables in one page. The scenario is, I have 3 tabs in a page, every tab contains DataTable service. I can show the datatable service in first tab (which is the index), and also implements DataTable js script for the next and third, it works but the problem is the next and third datatable are different from the first one. It's not showing any html services buttons ex: (create, upload, export etc..).  

Can you please tell how can we do this when using as service via Bootstrap Tabs/Pills?

Thanks,
Red :D

**Comment by marcelogarbin** [comment]
@sarfraznawaz2005 Are you still using this package? I'm also having difficulty using 2 tables in the same view. Table 1 works correctly, with searches and sorting, but Table 2 does not work the searches or sorting.
