### ISSUE TITLE
Using column filters with a join.

### ISSUE THREAD

**Issue by Petah** [yajra/laravel-datatables#374]
When using a join that has column names that are the same on 2 tables, I get an error:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'name' in where clause is ambiguous 
```

```
        $foo = \DB::table('foo')
            ->join('bar', 'bar.id', '=', 'foo.bar_id')
            ->select([
                'foo.id', 
                'foo.name', 
                'bar.name AS type', 
            ]);
        return \Yajra\Datatables\Datatables::of($foo)
            ->addColumn('action', function ($foo) {
                return '<a href="/foo/edit/'.$foo->id.'">Edit</a>';
            }, 0)
            ->make(true);
```

**Comment by Petah** [comment]
Setting the name on the column def seems to make this work, but it looks like that is actually vulnerable to sql injection (at least injecting a custom column name).

So a malicious user could run a query on a column that hasn't been explicitly allowed.

**Comment by yajra** [comment]
As per this [demo](http://datatables.yajrabox.com/eloquent/joins), you need to specify the column name when using join.

With regard to sql injection, the package uses Laravel's query builder which handles the SQL injection for us. And yes, running a query search with a column is possible even if not explicitly allowed but I guess it's not that harmful at all since it will only scope on the table you set on the builder? I am not a security expert so I am not really sure about it.

**Comment by Petah** [comment]
So are you saying its acceptable for a end user to be able to search on any column in the used tables?

I haven't tested it, but is this the same case for sorting?

**Comment by Petah** [comment]
BTW it might be nice to explicitly mention it on this page too, as it was the one I was using.

http://datatables.yajrabox.com/fluent/joins

**Comment by yajra** [comment]
Oh yeah, will mention it on that page too. Thanks!

For sorting, yes its the same. Datatables.js has this functionality too which allows you to order from a different column than what you click. Found the link, it's orderData. https://datatables.net/reference/option/columns.orderData

> So are you saying its acceptable for a end user to be able to search on any column in the used tables?

I am not saying that it's acceptable but I guess it's not harmful? And ordinary users can't do those queries since they cannot modify your javascript file? But then again, I admit that I am not a security expert so I am not really sure about this. Sorry about that! If you have some suggestions in mind. Please do not hesitate to submit a PR. Thanks!

**Comment by Petah** [comment]
So a quick example on why this is super bad. I wrote a script that can figure out the password hash of a user in your example pages.

Can you confirm if the users `flatley.trycia@hotmail.com` password hash starts with `aaapjqs`?

It took less than 1 minute to guess this far, and this is in no way an optimised attack. 

https://gist.github.com/Petah/6be822d195613fe02a5e

This is what it looks like at work:


```
C:\work\temp\dt-test>php find-passwords.php
Finding password hashes starting with a
Found 10 users
First user carroll.hermann@pfeffer.org
Finding password hashes starting with aa
Found 10 users
First user amir.email@yahoo.com
Finding password hashes starting with aaa
Found 1 users
First user flatley.trycia@hotmail.com
Finding password hashes starting with aaaa
Finding password hashes starting with aaab
Finding password hashes starting with aaac
Finding password hashes starting with aaad
Finding password hashes starting with aaae
Finding password hashes starting with aaaf
Finding password hashes starting with aaag
Finding password hashes starting with aaah
Finding password hashes starting with aaai
Finding password hashes starting with aaaj
Finding password hashes starting with aaak
Finding password hashes starting with aaal
Finding password hashes starting with aaam
Finding password hashes starting with aaan
Finding password hashes starting with aaao
Finding password hashes starting with aaap
Found 1 users
First user flatley.trycia@hotmail.com
Finding password hashes starting with aaapa
Finding password hashes starting with aaapb
Finding password hashes starting with aaapc
Finding password hashes starting with aaapd
Finding password hashes starting with aaape
Finding password hashes starting with aaapf
Finding password hashes starting with aaapg
Finding password hashes starting with aaaph
Finding password hashes starting with aaapi
Finding password hashes starting with aaapj
Found 1 users
First user flatley.trycia@hotmail.com
Finding password hashes starting with aaapja
Finding password hashes starting with aaapjb
Finding password hashes starting with aaapjc
Finding password hashes starting with aaapjd
Finding password hashes starting with aaapje
Finding password hashes starting with aaapjf
Finding password hashes starting with aaapjg
Finding password hashes starting with aaapjh
Finding password hashes starting with aaapji
Finding password hashes starting with aaapjj
Finding password hashes starting with aaapjk
Finding password hashes starting with aaapjl
Finding password hashes starting with aaapjm
Finding password hashes starting with aaapjn
Finding password hashes starting with aaapjo
Finding password hashes starting with aaapjp
Finding password hashes starting with aaapjq
Found 1 users
First user flatley.trycia@hotmail.com
Finding password hashes starting with aaapjqa
Finding password hashes starting with aaapjqb
Finding password hashes starting with aaapjqc
Finding password hashes starting with aaapjqd
Finding password hashes starting with aaapjqe
Finding password hashes starting with aaapjqf
Finding password hashes starting with aaapjqg
Finding password hashes starting with aaapjqh
Finding password hashes starting with aaapjqi
Finding password hashes starting with aaapjqj
Finding password hashes starting with aaapjqk
Finding password hashes starting with aaapjql
Finding password hashes starting with aaapjqm
Finding password hashes starting with aaapjqn
Finding password hashes starting with aaapjqo
Finding password hashes starting with aaapjqp
Finding password hashes starting with aaapjqq
Finding password hashes starting with aaapjqr
Finding password hashes starting with aaapjqs
Found 1 users
First user flatley.trycia@hotmail.com
Finding password hashes starting with aaapjqsa
Finding password hashes starting with aaapjqsb
Finding password hashes starting with aaapjqsc
... etc ...
```

**Comment by yajra** [comment]
Nice script but NO, the password hash for `flatley.trycia@hotmail.com` starts with `$2y$10$g` but it's quite correct since it's a wild card search `%aaapjqs%`. But then again, it's on developers discrepancy which field they want to return on json response so sensitive information like this should be hidden from response.

Anyways, will try to find a way to limit the column search to an explicitly allowed fields only. Thanks for the info. And please submit a PR if you have time and if possible. I think you are good at security stuffs and this will be easier for you. :+1:

**Comment by Petah** [comment]
Im not really sure how its up to "developers discrepancy" to prevent this because as far as i can see there is no way to prevent this, other than providing a table that didn't have extra columns that aren't public data. 

Ultimately I think the answer is only allowing whitelisted columns to be used in filters and sorts. I will have to have a look into either sending a PR or replacing this library as it is pretty much a show stopper.

**Comment by yajra** [comment]
@Petah, I just [committed](https://github.com/yajra/laravel-datatables/commit/212ba252ee6b0e7eb1909ca4c1f641e5a3ed2db8) on `dev-develop` branch that add a `blacklist` function where we can set which columns are restricted from sort & search. Can you please try if the proposed solution is acceptable for you? See example usage below:

```php
$users = User::query();

return Datatables::of($users)
    ->blacklist(['password', 'email'])
    ->make(true);
``` 

Let me know what you think. Feedbacks appreciated. Thanks!

**Comment by Petah** [comment]
Sorry I can't easily test this anymore, I had to replace this library with something else.

**Comment by yajra** [comment]
No problem. Anyways, thanks for the info on this thread. Cheers!
