### ISSUE TITLE
Conflict with other Datatables class in other package

### ISSUE THREAD

**Issue by ligne13** [yajra/laravel-datatables#464]
### Summary of problem or feature request

Hi, 

I had Yajra/Larvel-Datatables working well in my app. Today I installed the pragmarx/tracker third-party package and since then my use of Yajra/Datatables is broken because of a namespace conflict.

The bug happens on line of file 54 of file vendor/yajra/laravel-datatables-oracle/src/Datatables.php :

$datatables          = app('datatables');

This line will get the reference to the other Datatables library used in the pragmarx/tracker package.

This can be easily fixed with the following updated line 54 :

$datatables          = app('Yajra\Datatables\Datatables');

Can you fix that ? 
thanks

**Comment by KayCreations** [comment]
You changed the app() function from the Facade to the Real Class, but the real cause is in the  'pragmarx/tracker' Package.

The ServiceProvider of the tracker package tries to register a different DataTables Plugin
`$this->registerServiceProvider('Bllim\Datatables\DatatablesServiceProvider');`
`$this->registerServiceAlias('Datatable', 'Bllim\Datatables\Facade\Datatables');`

https://github.com/antonioribeiro/tracker/blob/master/src/Vendor/Laravel/ServiceProvider.php#L517

**Comment by ligne13** [comment]
OK, but I think it's better to specify the whole namespace when calling the app helper to avoid this kind of conflict.
Moreover, Yajra uses the full namespace later in the file (line 124) so it makes sens to use it before as well.

`return app('Yajra\Datatables\Html\Builder');`

https://github.com/yajra/laravel-datatables/blob/6.0/src/Datatables.php#L124

I've created a pull request : https://github.com/yajra/laravel-datatables/pull/465

**Comment by yajra** [comment]
Haven't tried pragmarx/tracker package but @KayCreations seems correct on the provider. Anyways, your PR was merged and released on v6.9.4. Thanks!

**Comment by ligne13** [comment]
great !
