### ISSUE TITLE
Datatables as a Service Documentation

### ISSUE THREAD

**Issue by nasirkhan** [yajra/laravel-datatables#478]
Rather than the general method i think the "Datatables as a Service" is more useful for me. But i could not find enough documentation on this. It would be great if you can describe how the existing doc can be useful in the service.

**Comment by yajra** [comment]
@nasirkhan, yes, I agree that the package still lacks documentation but I already have some plans to make a documentation like Laravel docs.

Anyways, all the demo are still applicable on service approach. That approach just separates the codes from controller to it's own DT class so that we can have smaller footprint and more readable code and some added features to support DT Buttons/TableTools extension.

Lastly, on `ajax` method of DT class, you can still use any codes as stated in the tutorial.

**Comment by vesper8** [comment]
I'm confused about a few things. Like I am trying to add the lengthMenu option so I can choose the number of entries that are paginated, but adding

```
            ->parameters([
                'dom' => 'Bfrtip',
                "lengthMenu" => [[10, 25, 50, -1], [10, 25, 50, "All"]],
                'scrollX' => true,
                'buttons' => [
                    'create', 'csv', 'excel', 'pdf', 'print', 'reset', 'reload'],
            ]);
```

seems to make no changes.. whereas the scrollX did work. I also don't know why the "search" field is activated.. I mean I like it.. and I want it.. but I can't tell where in the code it says to activate the search. So how do I activate the page length option using the "as a service" implementation?

**Comment by rossbearman** [comment]
Hi vesper8, you're missing the lowercase L flag from your 'dom' options, so the length menu won't show up. The following will make it appear after the buttons:
```
'dom'` => 'Blfrtip'
```

**Comment by vesper8** [comment]
Thanks man! I dug around to see if I could find all these options explained somewhere and found this https://datatables.net/reference/option/dom

**Comment by yajra** [comment]
Several demo for service approach were already added and will add more when I had the chance. Thanks!
