### ISSUE TITLE
Presenter Issue

### ISSUE THREAD

**Issue by shijupoothotta** [yajra/laravel-datatables#48]
I have a presenter 
trait StringPresenter {

    public function getFullnameAttribute() {
        return ucfirst($this->fname) . ' ' . ucfirst($this->lname);
    }

}

Controller
public function getData() {
        $providers = Provider::select(['fullname', 'email','type','status','created_at'])->get();
        return Datatables::of($providers)
        ->make();        
    }

Getting the debug error:
Unknown column 'fullname' in 'field list' .
But created_at trait is working fine.

**Comment by yajra** [comment]
`fullname` is a custom attribute and not an actual field so you should not include it on select statement. If you want to include it then you should concat it on the database side via query. Another way is to select both `fname` and `lname` then `editColumn('lname' , ''{{ $fname.' '.$lname }})`. Or you can also do this via the custom presenter. 

```php
public function getData() {
$providers = Provider::select(['fname','lname', 'email','type','status','created_at']);
return Datatables::of($providers)
->addColumn('fullname`, function($model) {
   return $model->fullname;
})
->make();

}
```

Or you can also concat it using js
```js
{data: function(data) { return data.fname + ' ' + data.lname; }, name: 'fname'}
```

Also, I suggest that you remove the `get()` method on your model so that you will Eloquent instead of Collection for better performance.

**Comment by shijupoothotta** [comment]
Yes , it is cleared. I assume that $model will be injected in the closure. It will be an instance of the 'provider'.

Is there any method to change the order of the newly added column, within the controller.

**Comment by shijupoothotta** [comment]
Sorry: Just re-read the instructions:
<strong>You can add columns by using addColumn($column_name, $content, $order)</strong>

**Comment by yajra** [comment]
Hi regarding the re-order, i think that code above may not work anymore (will have to check). One way to re-order is use `make(true)` then on your JS declare the columns arrangement.

```js
columns: [
            {data: 'id', name: 'id'},
            {data: 'name', name: 'name'},
            {data: 'email', name: 'email'},
            {data: 'created_at', name: 'created_at'},
            {data: 'updated_at', name: 'updated_at'}
        ]
```
