### ISSUE TITLE
414 (Request-URI Too Large)

### ISSUE THREAD

**Issue by semsphy** [yajra/laravel-datatables#540]
### Nginx status of 414 (Request-URI Too Large)

- Ubuntu 16.04
- PHP 7.0
- Laravel 5.2
- Laravel-Datatables ~6.0

**Comment by yajra** [comment]
Yes, this is possible to happen due to the design of the plugin. A quick google search appears that this can be fixed by configuring the server as suggested on [SO](http://stackoverflow.com/questions/2891574/how-do-i-resolve-a-http-414-request-uri-too-long-error). Another way is to use `post` method on your ajax request.
