### ISSUE TITLE
union of 2 models

### ISSUE THREAD

**Issue by kife-design** [yajra/laravel-datatables#573]
Hello,

Is there a possibillity to ad multiple models to 1 datatable? I have 2 models and i would like to add them both to the Datatables. These a fairly heavy tables so i would like to avoid using the collection method. Is this possible?

**Comment by yajra** [comment]
@kife-design, yeah I think it's possible if it's doable via Laravel's query builder. Having said that, I suggest you first create your union sql using Laravel's query builder and return the results. If it works, then you just need to pass the whole query to `Datatables` without the `get()` method to avoid using collection.

**Comment by yajra** [comment]
@kife-design I just recently implemented a DataTable using a union and thus this is indeed doable. A little snippet on my actual project, I have a custom query builder:

```php
public function query()
    {
        $connection = $this->getConnection();

        return $connection->table(
            $connection->raw('(' . $this->mainQuery()->toSql() . ')')
        )->select('*');
    }

public function mainQuery()
    {
        $q1 = $this->firstQuery();
        $q2 = $this->secondQuery();

        return $q1->unionAll($q2);
    }
```

On my DataTable:

```php
    public function query()
    {
        $builder = app(MyQueryBuilder::class);
        $query   = $builder->query();

        return $this->applyScopes($query);
    }
```

**Comment by TheTechnoMan** [comment]
Hello,

could you please tell me how your queries look like?

I have:

```
private function firstQuery()
{
    return $this->topic
        ->where('title', 'LIKE', '%'.'test'.'%')
        ->select(['message', 'created_at']);

}

private function secondQuery()
{
    return $this->reply
        ->where('message', 'LIKE', '%'.'test'.'%')
        ->select(['message', 'created_at']);
}
```

that results in this error:

SQLSTATE[42000]: Syntax error or access violation: 1248 Every derived table must have its own alias

I fixed that by changing the method to:

```
  public function query()
    {
        $connection = $this->getConnection();

        return $connection->table(
            $connection->raw('(' . $this->mainQuery()->toSql() . ') abc')
        )->select('*');
    }
```
now I get

`General error: 2031 (SQL: select count(*) as aggregate from (select * from ((select `message`, `created_at` from `topics` where `title` LIKE ? and `topics`.`deleted_at` is null) union all (select `message`, `created_at` from `replies` where `message` LIKE ? and `replies`.`deleted_at` is null)) abc) count_row_table)"}
`

Do you have any idea what the issue is? Any help would be highly appreciated..

Thanks
