### ISSUE TITLE
Presenter not applied

### ISSUE THREAD

**Issue by Propaganistas** [yajra/laravel-datatables#65]
As the title states; if any presenter has been defined, it won't get applied when returning models using `Datatables`.

I tried to apply the presenter on each item in a Collection:

```php
$blocks = Block::all()
$blocks->transform(function($model) { return AutoPresenter::decorate($model); });

return Datatables::of($blocks)->make(true);
```

but unfortunately an error is thrown stating that the presenter doesn't support array access:
 `Cannot use object of type BlockPresenter as array in yajra/Datatables/Engine/CollectionEngine.php:233`.

Probably converting the source code of laravel-datatables using object-relational retrieval of attributes will solve this...

**Comment by yajra** [comment]
Haven't tried `Presenter` on this package but I think it's only applicable on Eloquent? Can you try using `Book::get()` instead of `Book::all()`. Also, another way to decorate the output is by using [`league\fractal`](http://fractal.thephpleague.com/transformers/). Function to use is `setTransformer('App\Transformer\DataTransformer')`.

**Comment by Propaganistas** [comment]
Thanks for your reply. Presenters get applied to Eloquent models bound to views, paginator instances and Collections consisting of Eloquent models.

`get()` and `all()` both won't get "presented" when returned by Datatables.

Fractal will probably work, but aren't we just setting the same logic in two different places? It seems rather odd to me..

**Comment by yajra** [comment]
can you please provide the specific presenter package you are using. For Collection to work, it requires a `Collection` object and I think the transform method converts it to another `object`. I think you should turn it back to collection like:

```php
$blocks = Block::all()
$blocks->transform(function($model) { return AutoPresenter::decorate($model); });
$data = new Collection($blocks);

return Datatables::of($data)->make(true);
```

**Comment by yajra** [comment]
@Propaganistas I guess you are using [laravel-auto-presenter](https://github.com/laravel-auto-presenter/laravel-auto-presenter). I've checked the package and it seems that the decorators is just listening on view `content.rendering` event which causes the decorator to fail (not triggered) because we are not using `View` to display the datatables output. We are using `JsonResponse` here because the package is an API for Datatables. 

A workaround that I can think of for this to work is by overriding the `toArray` on your model and perform the decorations. But I'm checking the presenter package. I might me missing some things and I think it's a good feature to support it.

**Comment by yajra** [comment]
@Propaganistas laravel-auto-presenter is indeed not working on RESTful/API approach and presenter does not work because we do not render a view. https://github.com/laravel-auto-presenter/laravel-auto-presenter/issues/69

> @GrahamCampbell
Not sure what you mean. If you're not rendering a view, we can't automatically present your models for you. There's nothing special or magic about laravel. It's just php code.

> You can however, manually present your models using our facade, or by dependency injecting our presenter decorator class.

In this case, I suggest you use the `fractal` approach and create your own Transformer. But I'm accepting PR in case you have some idea on how to integrate the presenter package.
