### ISSUE TITLE
A quick question

### ISSUE THREAD

**Issue by yamilrevilla** [yajra/laravel-datatables#70]
Hi yajra, such a great package. Jesus man!!

I love the way this works on laravel but, is there a possibility to use this package outside laravel? I tried but did not work.

You think is there a work around to make this work on a project without laravel?

And btw sorry if I have grammar mistakes, not my native tongue :D

Cheers!

**Comment by yajra** [comment]
@yamilrevilla , thanks for the interest on the package. With regard to stand alone usage, sad to say that this may not work because the package relies heavily on Laravel's ORM, Query Builder, Collection, Facades, Helpers, etc...

On the other hand, I would consider this as an enhancement on future release if possible.
