### ISSUE TITLE
Using route::controller and resource at the same time

### ISSUE THREAD

**Issue by mcsaygili** [yajra/laravel-datatables#716]
Hi,
I made my controller via make:controller --resource. Then index page is data table. Other pages are static page. 

When i use like this,
```php
Route::resource('backend/haber', 'HaberController');
Route::controller('backend/haber', 'HaberController', [
        'getData'   => 'backend.haber.data',
    ]);
```
all pages are worked correctly expect datatable. (index)
if i change the location of route::controller 
```php
Route::controller('backend/haber', 'HaberController', [
        'getData'   => 'backend.haber.data',
    ]);
Route::resource('backend/haber', 'HaberController');
```
data table works fine, other pages not working. 

if I use only the route::controller there is many route parameters added my route.
like, 
backend/haber/data/{one?}/{two?}/{three?}/{four?}/{five?}

I want to use "RESTful Resource Controllers" (route::resource). How i can use like this ?

- Operating System : Windows 9.1 Pro (XAAMP)
- PHP Version : 5.6
- Laravel Version : 5.3
- Laravel-Datatables Version : Lastest

**Comment by yajra** [comment]
@mcsaygili You can use the approach like on this [demo](https://datatables.yajrabox.com/relation/has-one). What I usually do now is that the `index()` method of my resource controller handles all the operation for DT. And I do not recommend controller route since it's deprecated and will not work on Laravel 5.3

**Comment by mcsaygili** [comment]
Woow! You are really fast.  Thanks alot.

I got this error when i changed.

**Undefined property: App\Http\Controllers\Backend\HaberController::$dataTable**

Now my controller,
`public function index(Request $request){
        if ($request->ajax()) {
            $query = Haber::with('onePost')->select('haber.*');

            return $this->dataTable
                ->eloquent($query)
                ->addColumn('baslik', function (Haber $haber) {
                    return $haber->onePost ? str_limit($haber->onePost->baslik, 30, '...') : '';
                })
                ->make(true);
        }

        return view('backend.haber.index', [
            'title' => 'Has One Demo',
            'controller' => 'Haber Controller',
        ]);
    }`

**Comment by yajra** [comment]
I injected dataTable in the constructor. You can use the facade Datatable instead of $this->dataTable.

Sent from Outlook using iPhone




On Sun, Aug 28, 2016 at 2:35 PM +0800, "mcsaygili" <notifications@github.com> wrote:












Woow! You are really fast.  Thanks alot.



I got this error when i changed.



Undefined property: App\Http\Controllers\Backend\HaberController::$dataTable



Now my controller,

`public function index(Request $request){

        if ($request->ajax()) {

            $query = Haber::with('onePost')->select('haber.*');

        return $this->dataTable
            ->eloquent($query)
            ->addColumn('baslik', function (Haber $haber) {
                return $haber->onePost ? str_limit($haber->onePost->baslik, 30, '...') : '';
            })
            ->make(true);
    }

    return view('backend.haber.index', [
        'title' => 'Has One Demo',
        'controller' => 'Haber Controller',
    ]);
}`

**Comment by mcsaygili** [comment]
Yes, perfect. Thanks alot. 
BTW "DataTables as a Service Implementation" is my second solution.
