### ISSUE TITLE
Pagination of Large Datasets

### ISSUE THREAD

**Issue by JediMind** [yajra/laravel-datatables#796]
### Summary of problem or feature request

Working with a 15K records table. Is there a way to use offset and limit on my Eloquent model request and pass total amount of records as a variable to Laravel-Datatables for the pagination to display the correct stats? Right now it seems I have to provide all Collection items (which causes memory leaks) and Laravel-Datatables splices the Collection internally.

### System details

- Operating System: Windows 7 Ultimate
- PHP Version: 5.6
- Laravel Version: 5.2
- Laravel-Datatables Version: 6.19.0

**Comment by mikhi** [comment]
I have the same issue. In my case, the table holds 300K+ records.

**Comment by yajra** [comment]
I think this is a limitation of the PHP/Server resources and not really sure how optimize this. I only use collection when I am sure that the records will not exceed 1,000.

Question: Does your data really needs to be a collection? Why not use query builder approach?

**Comment by mikhi** [comment]
Query builder definitely works way better. This approach solved my problem, and my table with 300K+ records is successfully rendered.

Thanks,
Mihai

**Comment by mikhi** [comment]
JediMind, my code looks now something like:

instead of 
$obj = ModelName::all() 
now i use 
$obj = ModelName::query()->yourScope1()->yourScope2();
...........
return Datatables::of($obj)
->setTotalRecords($obj->count())
->make(true);

Hope this will help you.

**Comment by JediMind** [comment]
Answer: I must admit I used Datatables a bit out of its purpose. My Collection is actually made of a single data column containing rendered html. But mikhi and you yajra, shed light on the fact I should rethink my design and use query builder.  

->setTotalRecords seems to be what I was looking for in the beginning.

Thanks!

**Comment by marcstreeter** [comment]
In our case we couldn't use `querybuilder`. We are using a feature specific to Postgres that it doesn't currently express.  

Instead of doing `\DataTables::collection(<DB::raw(query)>)` we override the `paging` function in `CollectionDataTable`.  Our overridden version of `CollectionDataTable::paging` would then always return full results (instead of slicing since the limit had already been performed within the query).  And then instead of calling `\DataTables::collection(...)` we call `OurNewVersionOfDataTable::create(<DB::raw(query)>)` (which will eventually try to call `paging` and get the full paged result.  We still had to `setTotalRecords` as mentioned above, but with those parts in place it no longer crashes with our ~100k rows and still allows us to provide the correct number of records to `setTotalRecords` while being able to go to different pages (originally it would only work on the first page and then fail on the others).

**Comment by mateusfig** [comment]
> JediMind, my code looks now something like:
> 
> instead of
> `$obj = ModelName::all()`
> now i use
> `$obj = ModelName::query()->yourScope1()->yourScope2();`
> ...........
> `return Datatables::of($obj) ->setTotalRecords($obj->count()) ->make(true);`
> 
> Hope this will help you.

So cool! This helped me quite and finished my 48h struggle to make datatable render the page fastly. Before, the datatable based on a 70.000+ table registers was sooooo slow.

All I did (bold) and worked like a charm:

$ag=Agenda::query()->select($columns)**->limit(1)**;

 return datatables()->of($ag)
				**->setTotalRecords($obj->count())**
                               ->make(true);

Thank you so much!
