### ISSUE TITLE
Reduce the payload size?

### ISSUE THREAD

**Issue by sunscreem** [yajra/laravel-datatables#818]
Is there a way to reduce the payload size being returned? I don't need ALL the data from my models returned, nor the queries that were ran etc.

```php
return Datatables::of(Order::query()->with(['user','products']))->take(true);
```

**Comment by yajra** [comment]
4 ways that I can think you can use to reduce the payload.

* Use [transformer](https://datatables.yajrabox.com/eloquent/transformer).
* Manually set the selected fields on your query.
```php
return Datatables::of(
		Order::query()
			->select(['columns...'])
			->with([
				'user' => function($q) {
					$q->select(['cols..'])
				},
				'products' => function($q) {
					$q->select(['cols..'])
				},
			])
	)->make(true);
```
* Set the hidden fields on your model so that they will not be part of the response.
* Mix the 3 options above if it make sense.

**Comment by sunscreem** [comment]
Of course! `$hidden` fields in laravel stops them going out on as json. Totally forgot about that. I'll try it straight away.

**Comment by sunscreem** [comment]
@yajra Thank you Sir. The `$visible` method on my modal was the part I needed to remember.
