### ISSUE TITLE
PHP7.0 error on Request.php

### ISSUE THREAD

**Issue by imknight** [yajra/laravel-datatables#857]
sample url is something like http://domain.com/sales/data?limit=31&offset=0&order=asc

the same controller able to show data under HHVM and PHP5.X setup, but not on PHP7.0

the error show on Request.php line 76 and 77 with the error message

ErrorException in Request.php line 76:
Illegal string offset 'column'

**Comment by yajra** [comment]
@imknight thanks for reporting. May I know how you use the package? Using standard js, the columns should be sent automatically in the server. 

Anyways, will to look at at this asap. Thanks!

**Comment by imknight** [comment]
using it in controller like         

return Datatables::of($this->petrol->all())->make(true);

**Comment by yajra** [comment]
How about the javascript side?

**Comment by imknight** [comment]
using bootstrap-table to fetch it, but does this related to js ? because on the controller level the data return already causing the error ?

**Comment by yajra** [comment]
Yes, this might be related to js since the jquery library is the one sends the column variables to server.

Using the standard datatables.js, I think this url: `http://domain.com/sales/data?limit=31&offset=0&order=asc` is basically invalid/not a standard format. 

Would you be able to provide some snippet to reproduce the issue? Thanks!

**Comment by imknight** [comment]
testing the same data url on HHVM and PHP5.X setup without any problem, it will just return the json data nicely. but on PHP 7 server the error show.

**Comment by yajra** [comment]
Fix released on v6.22.1. Thanks!
