### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by spescina** [yajra/laravel-datatables#900]
A simple question.

How can you keep going on without a test suite?

**Comment by yajra** [comment]
Well, its a bit hard to keep going due to lack of test suite. Every PR I received is being countered check using the demo app I created which in turns becomes the documentation of the package.

A little history, this package was originally forked from https://github.com/bllim/laravel4-datatables-package and I am the one who submitted a PR for a simple unit tests. But since then, I was not able to add more test suite coz I am not really knowledgable on test suites per se. But it is in my plan to improve my coding skills by adding unit tests and been reading about it lately. Seen some testing stuffs done by [Adam Wathan](adamwathan.me/2016/01/11/test-driven-laravel-from-scratch/) and maybe will subscribe to his [course](https://adamwathan.me/test-driven-laravel/) when I get some funds ^_^.

**Comment by spescina** [comment]
I'm not a wizard in test suites but I can help

**Comment by yajra** [comment]
@spescina I would gladly accept a PR for some test suites. It will surely help the community. Thanks for offering some help!
